services:
  postgres:
    image: postgres:17.5
    # restart: unless-stopped
    container_name: getalaw-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    # volumes:
      # - postgres_data:/var/lib/postgresql/data

# volumes:
  # postgres_data: